version: '3.8'

services:
  app-1:
    build: .
    ports:
      - "5001:5000"
    networks:
      - rejuve-task

  app-2:
    build: .
    ports:
      - "5002:5000"
    networks:
      - rejuve-task

  app-3:
    build: .
    ports:
      - "5003:5000"
    networks:
      - rejuve-task

networks:
  my-network:
    driver: bridge
