version: '3.8'

services:
  app1:
    build: .
    networks:
      - rejuve-task

  app2:
    build: .
    networks:
      - rejuve-task

  app3:
    build: .
    networks:
      - rejuve-task
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - rejuve-task

networks:
  rejuve-task:
    driver: bridge
